name: Rich Codex
on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/rich-codex.yaml
      - README.md
      - perdoo/cli/**
  push:
    branches:
      - main
    paths:
      - .github/workflows/rich-codex.yaml
      - README.md
      - perdoo/cli/**
  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
env:
  PY_VERSION: '3.10'
permissions: {}

jobs:
  rich_codex:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@v8.3.2
        with:
          python-version: ${{ env.PY_VERSION }}
      - name: Install project
        run: uv sync --locked --dev --all-extras --managed-python
      - name: Generate terminal images with rich-codex
        uses: ewels/rich-codex@v1.3.1
        with:
          commit_changes: true
          clean_img_paths: docs/img/*.svg
